DROP TABLE IF EXISTS cms_content_version;
DROP TABLE IF EXISTS cms_content;
DROP TABLE IF EXISTS feature_checkin_success;
DROP TABLE IF EXISTS feature_checkin_failure;
DROP TABLE IF EXISTS feature_checkin;
DROP TABLE IF EXISTS feature_checkin_question_possible_answer;
DROP TABLE IF EXISTS feature_checkin_question;
DROP TABLE IF EXISTS feature_favourite;
DROP TABLE IF EXISTS feature_content_image;
DROP TABLE IF EXISTS feature_content ;
DROP TABLE IF EXISTS item_has_string_field ;
DROP TABLE IF EXISTS item_has_text_field ;
DROP TABLE IF EXISTS item_has_html_field ;
DROP TABLE IF EXISTS item ;
DROP TABLE IF EXISTS feature_has_event ;
DROP TABLE IF EXISTS event ;
DROP TABLE IF EXISTS organisation_has_admin ;
DROP TABLE IF EXISTS organisation ;
DROP TABLE IF EXISTS collection_has_field  ;
DROP TABLE IF EXISTS collection  ;
DROP TABLE IF EXISTS feature ;
DROP TABLE IF EXISTS user_session  ;
DROP TABLE IF EXISTS user_account  ;
DROP TABLE IF EXISTS migration;
